import {SELF,env} from 'cloudflare:test';
import {it,expect,describe} from 'vitest';
import {recordSeries,ensureDb} from '../src/accounts';
const username=()=>('u'+crypto.randomUUID().replaceAll('-','')).slice(0,18);
const post=(path:string,input:unknown,cookie='',ip=crypto.randomUUID())=>SELF.fetch('https://game.test/api/'+path,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json',cookie,'cf-connecting-ip':ip},body:JSON.stringify(input)});
async function signup(){const user=username(),res=await post('signup',{username:user,password:'Mesa-correct-horse-2026',name:'Ana'});expect(res.status).toBe(200);return {user,body:await res.json() as any,cookie:res.headers.get('set-cookie')!.split(';')[0]!};}
describe('optional persistent profiles',()=>{
 it('creates a profile and restores it via private HttpOnly session',async()=>{const s=await signup();const me:any=await (await SELF.fetch('https://game.test/api/me',{headers:{cookie:s.cookie}})).json();expect(me.profile.name).toBe('Ana');expect(me.profile.games).toBe(0);expect(me.profile.password_hash).toBeUndefined();expect(me.profile.salt).toBeUndefined();});
 it('rejects short passwords and cross-origin signup',async()=>{expect((await post('signup',{username:username(),password:'short'})).status).toBe(400);const r=await SELF.fetch('https://game.test/api/signup',{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:'{}'});expect(r.status).toBe(403);});
 it('supports login/logout and does not retain revoked sessions',async()=>{const s=await signup();const log=await post('login',{username:s.user,password:'Mesa-correct-horse-2026'});expect(log.status).toBe(200);expect(log.headers.get('set-cookie')).toContain('HttpOnly');expect((await post('login',{username:s.user,password:'not-the-right-password'})).status).toBe(401);await post('logout',{},s.cookie);const me:any=await (await SELF.fetch('https://game.test/api/me',{headers:{cookie:s.cookie}})).json();expect(me.profile).toBeNull();});
 it('saves name/country and private age, without client-controlled wins',async()=>{const s=await signup();const result:any=await (await post('profile',{name:'Ana María',country:'Dominican Republic',ageBand:'35–44',avatar:1,wins:999},s.cookie)).json();expect(result.profile.name).toBe('Ana María');expect(result.profile.wins).toBe(0);expect(result.profile.ageBand).toBe('35–44');const pub:any=await (await SELF.fetch('https://game.test/api/profile?id='+s.body.profile.id)).json();expect(pub.profile.country).toBe('Dominican Republic');expect(pub.profile.ageBand).toBeUndefined();expect(pub.profile.password_hash).toBeUndefined();});
 it('rejects unauthenticated edits',async()=>{expect((await post('profile',{name:'hijack',country:'',ageBand:'',avatar:0})).status).toBe(401);});
 it('counts server-verified series exactly once across retries',async()=>{const s=await signup();await ensureDb(env as any);const id=crypto.randomUUID(),parts=[{id:s.body.profile.id,won:true,ownScore:207,opponentScore:93}];await recordSeries(env as any,id,parts);await recordSeries(env as any,id,parts);const me:any=await (await SELF.fetch('https://game.test/api/me',{headers:{cookie:s.cookie}})).json();expect(me.profile.games).toBe(1);expect(me.profile.wins).toBe(1);expect(me.profile.losses).toBe(0);});
});
