import {SELF} from 'cloudflare:test';
import {describe,it,expect} from 'vitest';
const credential=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');
const unique=()=>crypto.randomUUID();
async function open(room:string){const r=await SELF.fetch(`https://game.test/ws/${room}`,{headers:{Upgrade:'websocket'}});expect(r.status).toBe(101);const ws=r.webSocket!;ws.accept();const frames:any[]=[];ws.addEventListener('message',e=>{if(e.data!=='__pong')frames.push(JSON.parse(String(e.data)));});const next=async(test:(f:any)=>boolean)=>{for(let i=0;i<200;i++){const index=frames.findIndex(test);if(index>=0)return frames.splice(index,1)[0];await scheduler.wait(10);}throw Error('Timed out: '+JSON.stringify(frames));};return {ws,frames,send:(m:any)=>ws.send(JSON.stringify(m)),next,state:()=>next(f=>f.type==='state'),error:()=>next(f=>f.type==='error')};}
async function host(room:string){const h=await open(room),token=credential();h.send({type:'join',role:'host',token});const state=await h.state();expect(state.view.isHost).toBe(true);return {...h,token};}
describe('Mesa authoritative room',()=>{
 it('guards routes and rejects malformed messages',async()=>{expect((await SELF.fetch('https://game.test/ws')).status).toBe(426);const h=await open(unique());h.ws.send('bad json');expect((await h.error()).error).toMatch(/Invalid/);h.send({type:'action',action:{type:'start'}});expect((await h.error()).error).toMatch(/Join/);h.ws.close();});
 it('opens a host display without occupying a seat; QR guests get their private hands only',async()=>{const room=unique(),h=await host(room),people=[];for(let i=0;i<4;i++){const p=await open(room);p.send({type:'join',role:'player',token:credential(),name:'Player '+i});const s=await p.state();expect(s.view.seat).toBe(i);people.push(p);}h.send({type:'action',action:{type:'start'}});const shared=await h.next(f=>f.type==='state'&&f.view.phase==='playing');expect(shared.view.hand).toEqual([]);expect(shared.view.counts).toEqual([7,7,7,7]);expect(shared.view.seed).toBeUndefined();const states=[];for(const p of people){const s=await p.next(f=>f.type==='state'&&f.view.phase==='playing');expect(s.view.hand.length).toBe(7);expect(s.view.revealed).toBeNull();states.push(s);}expect(new Set(states.flatMap(s=>s.view.hand.map((t:any)=>t.id))).size).toBe(28);const turn=shared.view.turn;people[turn]!.send({type:'action',action:{type:'play',tile:'6-6',side:'right'}});const after=await h.next(f=>f.type==='state'&&f.view.chain.length===1);expect(after.view.chain[0].id).toBe('6-6');expect(after.view.hand).toEqual([]);people.forEach(p=>p.ws.close());h.ws.close();});
 it('requires a private credential to reclaim a seat; cannot claim a public name',async()=>{const room=unique(),h=await host(room),a=await open(room),token=credential();a.send({type:'join',role:'player',name:'Ana',token});expect((await a.state()).view.seat).toBe(0);a.ws.close();const back=await open(room);back.send({type:'join',role:'player',name:'Ana',token});expect((await back.state()).view.seat).toBe(0);const imposter=await open(room);imposter.send({type:'join',role:'player',name:'Ana',token:credential()});expect((await imposter.state()).view.seat).toBe(1);back.ws.close();imposter.ws.close();h.ws.close();});
 it('cannot change identity on an already joined connection',async()=>{const h=await host(unique());h.send({type:'join',role:'player',token:credential(),name:'Fake'});expect((await h.error()).error).toBe('Already joined.');h.ws.close();});
 it('does not let a spectator reset, deal, alter settings, or obtain tiles',async()=>{const room=unique(),h=await host(room),s=await open(room);s.send({type:'join',role:'spectator',token:credential()});const v=await s.state();expect(v.view.seat).toBe(-1);expect(v.view.hand).toEqual([]);s.send({type:'action',action:{type:'start'}});expect((await s.error()).error).toMatch(/host/);s.send({type:'reset'});expect((await s.error()).error).toMatch(/Unknown/);h.ws.close();s.ws.close();});
 it('refuses malformed credentials and guests in unopened rooms',async()=>{const a=await open(unique());a.send({type:'join',role:'host',token:'abc'});expect((await a.error()).error).toMatch(/credential/);a.send({type:'join',role:'player',token:credential(),name:'Ana'});expect((await a.error()).error).toMatch(/not open/);a.ws.close();});
 it('keeps rooms isolated',async()=>{const a=await host(unique()),b=await host(unique());a.send({type:'action',action:{type:'start'}});expect((await a.next(f=>f.type==='state'&&f.view.phase==='playing')).view.handNo).toBe(1);b.send({type:'action',action:{type:'settings',settings:{target:100,capicua:0,tie:'none',allPips:false}}});const second=await b.next(f=>f.type==='state'&&f.view.settings.target===100);expect(second.view.phase).toBe('lobby');expect(second.view.handNo).toBe(0);a.ws.close();b.ws.close();});
});
