import {describe,it,expect} from 'vitest';
import {DIM,chainLayout,footprint,idleMotion,seats,type BoardTile,type BoardMove,type Placement} from '../src/scene-layout';
function trail(seed:number,mode:'left'|'right'|'mixed'){
 let s=seed;const rand=()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};const edges:{id:string;a:number;b:number}[]=[];for(let a=0;a<=6;a++)for(let b=a;b<=6;b++)if(a!==6||b!==6)edges.push({id:a+'-'+b,a,b});
 const stack:{node:number;edge:BoardTile|null}[]=[{node:6,edge:null}],reverse:BoardTile[]=[];
 while(stack.length){const cur=stack[stack.length-1]!,opts=edges.map((e,i)=>({e,i})).filter(({e})=>e.a===cur.node||e.b===cur.node);if(opts.length){const {e,i}=opts[Math.floor(rand()*opts.length)]!;edges.splice(i,1);const next=e.a===cur.node?e.b:e.a;stack.push({node:next,edge:{id:e.id,x:cur.node,y:next}});}else{const p=stack.pop()!;if(p.edge)reverse.push(p.edge);}}
 const remaining=reverse.reverse(),chain:BoardTile[]=[{id:'6-6',x:6,y:6}],moves:BoardMove[]=[{type:'play',tile:'6-6',side:'right'}],states=[{chain:[...chain],moves:[...moves]}];
 while(remaining.length){const left=mode==='left'||(mode==='mixed'&&rand()<.5),tile=(left?remaining.pop():remaining.shift())!;if(left)chain.unshift(tile);else chain.push(tile);moves.push({type:'play',tile:tile.id,side:left?'left':'right'});states.push({chain:[...chain],moves:[...moves]});}return states;
}
describe('traditional domino placement',()=>{
 it('anchors opening double in the middle, crosswise',()=>{const p=chainLayout([{id:'6-6',x:6,y:6}])[0]!;expect(p.x).toBe(0);expect(p.z).toBe(0);expect(p.vertical).toBe(true);expect(p.isDouble).toBe(true);});
 it('grows left and right with matching end orientation and crosswise doubles',()=>{const chain=[{id:'4-4',x:4,y:4},{id:'4-6',x:4,y:6},{id:'6-6',x:6,y:6},{id:'3-6',x:6,y:3},{id:'3-3',x:3,y:3}],moves=[{type:'play',tile:'6-6',side:'right'},{type:'play',tile:'4-6',side:'left'},{type:'play',tile:'3-6',side:'right'},{type:'play',tile:'4-4',side:'left'},{type:'play',tile:'3-3',side:'right'}];const p=chainLayout(chain,moves);expect(p[0]!.x).toBeLessThan(p[1]!.x);expect(p[1]!.x).toBeLessThan(0);expect(p[2]!.x).toBe(0);expect(p[3]!.x).toBeGreaterThan(0);expect(p[4]!.x).toBeGreaterThan(p[3]!.x);for(const i of [0,2,4])expect(p[i]!.vertical).toBe(true);});
 it('keeps existing positions absolutely fixed for all prefixes and growth patterns',()=>{for(let seed=1;seed<=25;seed++)for(const mode of ['left','right','mixed'] as const){const previous=new Map<string,Placement>();for(const state of trail(seed,mode)){for(const p of chainLayout(state.chain,state.moves)){if(previous.has(p.id))expect(p).toEqual(previous.get(p.id));previous.set(p.id,p);}}}});
 it('keeps full double-six layouts within felt and free of overlap',()=>{for(let seed=1;seed<=50;seed++)for(const mode of ['left','right','mixed'] as const){const state=trail(seed,mode)[27]!,placed=chainLayout(state.chain,state.moves),rs=placed.map(footprint);expect(placed).toHaveLength(28);for(const r of rs)expect(Math.max(Math.abs(r.left),Math.abs(r.right),Math.abs(r.top),Math.abs(r.bottom))).toBeLessThan(DIM.feltWidth/2-.02);for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++){const a=rs[i]!,b=rs[j]!;expect(Math.min(a.right,b.right)-Math.max(a.left,b.left)>.00001&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>.00001).toBe(false);}}});
 it('connects actual chain neighbors through straight runs and edge turns',()=>{for(let seed=1;seed<=20;seed++){const state=trail(seed,'mixed')[27]!,p=chainLayout(state.chain,state.moves),rs=p.map(footprint);for(let i=1;i<rs.length;i++){const a=rs[i-1]!,b=rs[i]!,dx=Math.max(0,a.left-b.right,b.left-a.right),dz=Math.max(0,a.top-b.bottom,b.top-a.bottom);expect(Math.hypot(dx,dz)).toBeLessThanOrEqual(DIM.tileGap+.00001);}}});
 it('turns doubles perpendicular to growth and orients normal tile values correctly',()=>{for(let seed=1;seed<=15;seed++){const state=trail(seed,'mixed')[27]!;for(const p of chainLayout(state.chain,state.moves)){const dot=Math.cos(p.yaw)*p.dx-Math.sin(p.yaw)*p.dz;if(p.isDouble)expect(Math.abs(dot)).toBeLessThan(.00001);else expect(dot).toBeCloseTo(p.side==='left'?-1:1,5);}}});
 it('supports a non-double opener without inventing a double-six tile',()=>{const p=chainLayout([{id:'2-5',x:2,y:5}]);expect(p[0]!.isDouble).toBe(false);expect(p[0]!.vertical).toBe(false);expect(p[0]!.x).toBe(0);});
 it('keeps pips readable, racks off the felt and people outside table volume',()=>{expect(DIM.pipRadius*2/DIM.tileWidth).toBeGreaterThan(.18);expect(DIM.rackRadius).toBeGreaterThan(DIM.feltWidth/2);for(const s of seats)expect(Math.max(Math.abs(s[0]!),Math.abs(s[1]!))-DIM.tableWidth/2).toBeGreaterThan(.28);});
});
describe('independent bounded idle motion',()=>{
 it('uses independent player motion',()=>{for(const t of [0,3,9,20,50,120])expect(new Set([0,1,2,3].map(i=>JSON.stringify(idleMotion(i,t)))).size).toBe(4);});
 it('bounds every character for three minutes, without a torso bow',()=>{for(let t=0;t<180;t+=.125)for(let i=0;i<12;i++){const m=idleMotion(i,t);expect(Math.abs(m.breath)).toBeLessThanOrEqual(.0056);expect(Math.abs(m.headYaw)).toBeLessThanOrEqual(.116);expect(Math.abs(m.headNod)).toBeLessThanOrEqual(.010);}});
 it('respects reduced motion',()=>expect(idleMotion(2,50,true)).toEqual({breath:0,headYaw:0,headNod:0}));
});
