import {describe,it,expect}from'vitest';import{SELF}from'cloudflare:test';import{TokenVerifier}from'livekit-server-sdk';import{joinVoice,voiceConfigured}from'../src/voice';
const setup={LIVEKIT_URL:'wss://voice.example.invalid',LIVEKIT_API_KEY:'local-test-key',LIVEKIT_API_SECRET:'not-a-real-secret-only-for-isolated-tests-2026'} as any;
const member={id:'public-neighbor',name:'Ana',role:'player',seat:2,crowdIndex:-1,muted:false};
describe('proximity voice setup and permissions',()=>{
 it('is clearly unavailable until production credentials exist',async()=>{expect(voiceConfigured({} as any)).toBe(false);const r:any=await(await SELF.fetch('https://game.test/api/voice-config')).json();expect(r.available).toBe(false);expect(r.proximity).toBe(true);});
 it('issues microphone-only room-scoped grants with immutable seat metadata',async()=>{const result=await joinVoice(setup,'table1',member);const claims:any=await new TokenVerifier(setup.LIVEKIT_API_KEY,setup.LIVEKIT_API_SECRET).verify(result.token);expect(claims.video.room).toBe('mesa-table1');expect(claims.video.canPublish).toBe(true);expect(claims.video.canPublishSources).toEqual(['microphone']);expect(claims.video.canPublishData).toBe(false);expect(claims.video.canUpdateOwnMetadata).toBe(false);expect(JSON.parse(claims.metadata)).toEqual({role:'player',seat:2,crowdIndex:-1});expect(claims.video.roomAdmin).toBeUndefined();});
 it('does not let microphone-source permission override a host mute',async()=>{const result=await joinVoice(setup,'table1',{...member,muted:true});const claims:any=await new TokenVerifier(setup.LIVEKIT_API_KEY,setup.LIVEKIT_API_SECRET).verify(result.token);expect(claims.video.canPublish).toBe(false);expect(claims.video.canPublishSources).toBeUndefined();});
 it('rejects cross-origin token requests before touching voice infrastructure',async()=>{const r=await SELF.fetch('https://game.test/api/voice-token',{method:'POST',headers:{origin:'https://other.test'},body:'{}'});expect(r.status).toBe(403);});
 it('does not expose internal room token endpoint publicly',async()=>{expect((await SELF.fetch('https://game.test/voice-token',{method:'POST',body:'{}'})).status).toBe(404);});
});
