import{chromium}from'@playwright/test';import fs from'node:fs/promises';
const base='http://localhost:8790';await fs.mkdir('qa',{recursive:true});const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader']});
try{
 const p=await browser.newPage({serviceWorkers:'block'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/scene.js*',r=>r.fulfill({contentType:'text/javascript',body:'export async function createWorld(){return {update(){},setCrowd(){},setCamera(){},setMode(){},quality(){},ready:Promise.resolve(),dispose(){}}}'}));
 const layouts=[];for(const [width,height]of[[1440,774],[1366,768],[1280,720],[390,844],[360,640],[844,390]]){await p.setViewportSize({width,height});await p.goto(base,{waitUntil:'domcontentloaded'});await p.locator('[data-action="host"]').waitFor();await p.evaluate(()=>document.fonts.ready);const r=await p.evaluate(()=>({buttons:[...document.querySelectorAll('.title-actions button,.title-secondary button')].map(x=>{const r=x.getBoundingClientRect();return{label:x.textContent,bottom:r.bottom,top:r.top,left:r.left,right:r.right}}),overflow:document.documentElement.scrollWidth>innerWidth+1,titleLines:document.querySelectorAll('.title-screen h1 span').length}));if(r.overflow||r.titleLines!==2||r.buttons.some(b=>b.bottom>height-7||b.top<65||b.left<0||b.right>width))throw Error('Clipped controls: '+JSON.stringify({width,height,r}));if(r.buttons[3].top<r.buttons[2].bottom-1)throw Error('Menu links overlap the last button');layouts.push({width,height,pass:true});}
 await p.setViewportSize({width:1280,height:800});await p.goto(base,{waitUntil:'domcontentloaded'});await p.evaluate(()=>{window.voiceEvents=[];window.panners=[];const create=AudioContext.prototype.createPanner;AudioContext.prototype.createPanner=function(){const p=create.call(this);window.panners.push(p);return p};window.addEventListener('mesa:botvoice',e=>window.voiceEvents.push(e.detail));});await p.locator('[data-action="settings"]').click();await p.locator('[data-action="bot-voice-demo"]').click();await p.waitForFunction(()=>window.voiceEvents.filter(e=>!e.active).length===4,null,{timeout:20000});const voices=await p.evaluate(()=>({speakers:window.voiceEvents.filter(e=>e.active).map(e=>e.seat),modes:window.panners.map(p=>p.panningModel),positions:window.panners.map(p=>[p.positionX.value,p.positionY.value,p.positionZ.value])}));if(new Set(voices.speakers).size!==4||voices.modes.some(x=>x!=='HRTF'))throw Error('Voice preview/spatialization failed');await p.locator('[data-action="close"]').first().click();
 await p.locator('[data-action="host"]').click();await p.locator('#qr svg').waitFor();await p.locator('[data-vaction="panel"]').click();await p.locator('[data-vaction="connect"]').click();await p.getByText('Your microphone is still off.',{exact:false}).waitFor();await p.locator('[data-vaction="close"]').click();
 const real=await browser.newPage({viewport:{width:1440,height:850},serviceWorkers:'block'});real.on('pageerror',e=>errors.push(e.message));await real.goto(base,{waitUntil:'domcontentloaded'});await real.waitForFunction(()=>window.mesaDiagnostics?.characters===4,null,{timeout:90000});await real.screenshot({path:'qa/colmado-polish.png',timeout:60000});await real.locator('[data-action="practice"]').click();await real.waitForTimeout(14000);await real.screenshot({path:'qa/table-polish.png',timeout:60000});console.log(JSON.stringify({pass:true,layouts,voices,errors,scene:await real.evaluate(()=>window.mesaDiagnostics)},null,2));if(errors.length)throw Error(errors.join(';'));
}finally{await browser.close();}
