import{chromium}from'@playwright/test';import fs from'node:fs/promises';
const base=process.env.MESA_URL||'http://localhost:8788';await fs.mkdir('qa',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader']});
const errors=[];const track=p=>p.on('pageerror',e=>errors.push(e.message));
// Primary table uses the actual renderer. Secondary spectator/account browser
// tabs stub only rendering, so UI/protocol tests do not compete for software GPU.
async function noRendering(p){await p.route('**/scene.js*',r=>r.fulfill({contentType:'text/javascript',body:'export async function createWorld(){return {update(){},setCrowd(){},setCamera(){},setMode(){},quality(){},ready:Promise.resolve(),dispose(){}}}'}));}
try{
 const host=await browser.newPage({viewport:{width:1100,height:760}});track(host);await host.goto(base);await host.locator('[data-action="host"]').waitFor();await host.locator('[data-action="host"]').click();await host.locator('#qr svg').waitFor({timeout:30000});const room=new URL(host.url()).searchParams.get('room');
 const phoneCtx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),phone=await phoneCtx.newPage();track(phone);await phone.goto(`${base}/?room=${room}&role=player`);await phone.getByLabel('Your name').fill('Ana');await phone.getByRole('button',{name:'Take my seat'}).click();await phone.getByText('You’re at the table.').waitFor();await host.locator('.seat-row').filter({hasText:'Ana'}).waitFor();
 const watcher=await browser.newPage({viewport:{width:900,height:700}});await noRendering(watcher);track(watcher);await watcher.goto(`${base}/?room=${room}&role=spectator`);await watcher.getByLabel('Your name').fill('Paco');await watcher.getByRole('button',{name:'Join the crowd'}).click();await host.waitForFunction(()=>document.querySelector('#viewer-count')?.textContent==='1');
 await watcher.locator('[data-action="chat"]').click();await watcher.getByLabel('Message to the table').fill('Dale, que la noche es joven.');await watcher.getByRole('button',{name:'Send message'}).click();await host.locator('.chat-bubble').filter({hasText:'Dale, que la noche es joven.'}).waitFor();
 await host.locator('[data-action="chat"]').click();await host.locator('[data-action="feature"]').click();await host.getByText('CORNER SPOTLIGHT').waitFor();await host.locator('[data-action="crowd-mute"]').click();if(await host.locator('.chat-message').count())throw Error('Crowd mute did not suppress messages');await host.locator('[data-action="crowd-mute"]').click();await host.locator('.chat-message').waitFor();await host.locator('[data-action="chat"]').click();
 await host.locator('[data-action="start"]').click();await phone.locator('.hand-panel').waitFor();if(await phone.locator('.hud-score,.board,#world canvas').count())throw Error('Phone is not tiles-only');if(await host.locator('.hand-panel').count())throw Error('Host private hand leak');await phone.screenshot({path:'qa/alpha2-phone.png'});
 await host.waitForFunction(()=>window.mesaDiagnostics?.characters===4&&window.mesaDiagnostics?.visibleCrowd===1,null,{timeout:60000});console.log('scene',JSON.stringify(await host.evaluate(()=>window.mesaDiagnostics)));await host.screenshot({path:'qa/alpha2-crowd.png',timeout:60000});
 let actions=0;for(let i=0;i<170;i++){if(await host.locator('.game-result').count())break;const legal=phone.locator('.tile-button.legal');if(await legal.count()){await legal.first().click();await phone.locator('[data-play]').first().click();actions++;}else if(await phone.locator('[data-action="pass"]').count()){await phone.locator('[data-action="pass"]').click();actions++;}await phone.waitForTimeout(700);}
 await host.locator('.game-result').waitFor({timeout:15000});await host.getByRole('button',{name:'Deal the next hand'}).click();await phone.locator('.hand-panel').waitFor();await phone.reload({waitUntil:'domcontentloaded'});await phone.locator('.hand-panel').waitFor();
 const account=await browser.newPage({serviceWorkers:'block'});await noRendering(account);track(account);await account.goto(base);await account.locator('[data-action="profile"]').click();await account.locator('[data-auth="signup"]').click();const username='test'+Date.now().toString(36);await account.getByLabel('Display name',{exact:true}).fill('Nora');await account.getByLabel('Username',{exact:true}).fill(username);await account.getByLabel('Password',{exact:true}).fill('Mesa-browser-test-2026');await account.getByRole('button',{name:'Create my profile'}).click();await account.locator('#profile-form').waitFor();await account.getByLabel('Country (optional)',{exact:true}).fill('Dominican Republic');await account.getByLabel('Age band (optional · private)').selectOption('35–44');await account.getByRole('button',{name:'Save profile'}).click();await account.waitForTimeout(500);await account.reload({waitUntil:'domcontentloaded'});await account.locator('[data-action="profile"]').click();await account.locator('#profile-form').waitFor();if(await account.getByLabel('Country (optional)',{exact:true}).inputValue()!=='Dominican Republic')throw Error('Profile did not persist');await account.screenshot({path:'qa/alpha2-profile.png'});
 await phone.locator('[data-action="school"]').click();await phone.locator('[data-answer="1"]').click();await phone.getByText('Eso es.',{exact:false}).waitFor();
 if(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Phone horizontal overflow');
 console.log(JSON.stringify({pass:true,actions,browserErrors:errors,checks:['real 3D characters loaded','crowd visual matches spectator connection','table text chat','crowd mute','host spotlight','QR join','tiles-only phone','private-hand redaction','full scored hand','next deal','seat reload','profile signup/update/reload','lesson quiz']},null,2));if(errors.length)throw Error(errors.join('\n'));
}finally{await browser.close();}
